# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Configuration for Folder Extractor
# https://docs.coderabbit.ai

language: de

reviews:
  profile: assertive  # chill or assertive

  auto_review:
    enabled: true

  path_filters:
    - "folder_extractor/**/*.py"
    - "tests/**/*.py"
    - "setup.py"
    - "!**/__pycache__/**"
    - "!**/*.pyc"
    - "!**/*.pyo"
    - "!**/*.pyd"
    - "!tests/fixtures/**"
    - "!.github/**"
    - "!.vscode/**"
    - "!.idea/**"

chat:
  auto_reply: true
